export const CLOUDINARY_CLOUD_NAME = 'YOUR_CLOUDINARY_CLOUD_NAME'
export const CLOUDINARY_USERS_FOLDER_ID = 'YOUR_CLOUDINARY_USERS_FOLDER_ID'
export const CLOUDINARY_POSTS_FOLDER_ID = 'YOUR_CLOUDINARY_POSTS_FOLDER_ID'